In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("urbankart_sales_messy.csv")

In [3]:
df.head()

,order_id,order_date,region,city,product_name,category,quantity,unit_price,total_revenue,customer_id,sales_channel
0,UK-2026-103168,2026-05-10,East,Patna,Matte Lipstick Set,Beauty,2.0,933,1866,CUST-68709,Marketplace
1,UK-2026-103684,2026-05-07,South,Chennai,Vitamin C Serum,Beauty,1.0,682,682,CUST-75684,App
2,UK-2026-104082,2026-06-21,South,Bengaluru,Wireless Earbuds Pro,Electronics,1.0,3107,3107,CUST-85468,Marketplace
3,UK-2026-101291,2026-02-18,South,Hyderabad,Electric Kettle 1.5L,Home & Kitchen,1.0,1122,1122,CUST-36533,App
4,UK-2026-101181,2026-02-18,Central,Raipur,Denim Jacket,Fashion,1.0,2196,2196,CUST-95981,Website

In [4]:
df.shape

(5150, 11)

In [5]:
df.columns

Index(['order_id', 'order_date', 'region', 'city', 'product_name', 'category',
       'quantity', 'unit_price', 'total_revenue', 'customer_id',
       'sales_channel'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5150 entries, 0 to 5149
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       5150 non-null   object
 1   order_date     5150 non-null   object
 2   region         5087 non-null   object
 3   city           5150 non-null   object
 4   product_name   5150 non-null   object
 5   category       5150 non-null   object
 6   quantity       5089 non-null   float64
 7   unit_price     5150 non-null   int64
 8   total_revenue  5089 non-null   object
 9   customer_id    5150 non-null   object
 10  sales_channel  5150 non-null   object
dtypes: float64(1), int64(1), object(9)
memory usage: 442.7+ KB

In [7]:
df.describe()

          quantity    unit_price
count  5089.000000   5150.000000
mean      1.381018   5961.211456
std       0.756030   8793.738391
min      -2.000000    428.000000
25%       1.000000   1142.250000
50%       1.000000   2103.500000
75%       2.000000   4664.000000
max       4.000000  31485.000000

In [8]:
df.isnull().sum()

order_id          0
order_date        0
region           63
city              0
product_name      0
category          0
quantity         61
unit_price        0
total_revenue    61
customer_id       0
sales_channel     0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(150)

In [10]:
df['city'].unique()

array(['Patna', 'Chennai', 'Bengaluru', 'Hyderabad', 'Raipur', 'Mumbai',
       'Delhi', 'Chandigarh', 'Noida', 'Bhubaneswar', 'Bhopal',
       'Ahmedabad', 'Guwahati', 'Nagpur', 'Kochi', 'Indore', 'Bangalore',
       'Pune', 'Surat', 'Gurugram', 'Kolkata', 'BLR', 'kochi', 'Gurgaon',
       'Madras', 'Cochin', 'New Delhi', 'bengaluru', 'patna', 'raipur',
       'GGN', 'Calcutta', 'CHANDIGARH', 'Bombay', 'Mumbai   ', '  Kochi',
       'chandigarh', 'Kolkata   ', 'Chandigarh   ', 'guwahati', 'DELHI',
       'chennai', 'surat', '  Ahmedabad', 'Surat   ', '  Chandigarh',
       '  Chennai', 'Chennai   ', 'Raipur   ', '  Noida', 'Noida   ',
       '  Bhubaneswar', 'PUNE', 'Kochi   ', '  Surat', '  Bhopal',
       'mumbai'], dtype=object)

In [11]:
# Step --> 1. Remove exact duplicate rows

In [12]:
df.duplicated().sum()

np.int64(150)

In [13]:
df=df.drop_duplicates()

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
# Step --> 2. Standardize all dates to YYYY-MM-DD

In [16]:
df.columns

Index(['order_id', 'order_date', 'region', 'city', 'product_name', 'category',
       'quantity', 'unit_price', 'total_revenue', 'customer_id',
       'sales_channel'],
      dtype='object')

In [17]:
df['order_date'].head(10)

0    2026-05-10
1    2026-05-07
2    2026-06-21
3    2026-02-18
4    2026-02-18
5    2026-03-23
6    2026-04-21
7    2026-05-21
8    2026-03-05
9    2026-06-13
Name: order_date, dtype: object

In [18]:
df['order_date'].tail(10)

5140    05/02/2026
5141    2026-03-01
5142    2026-01-13
5143    2026-05-30
5144    2026-06-04
5145    2026-05-05
5146    2026-01-04
5147    2026-05-10
5148    2026-05-27
5149    2026-01-27
Name: order_date, dtype: object

In [19]:
df['order_date']=pd.to_datetime(df['order_date'],format='mixed',dayfirst=True)

In [20]:
df['order_date'].tail(10)

5140   2026-02-05
5141   2026-03-01
5142   2026-01-13
5143   2026-05-30
5144   2026-06-04
5145   2026-05-05
5146   2026-01-04
5147   2026-05-10
5148   2026-05-27
5149   2026-01-27
Name: order_date, dtype: datetime64[ns]

In [21]:
df['order_date']=df['order_date'].dt.strftime("%Y-%m-%d")

In [22]:
df['order_date'].head(10)

0    2026-05-10
1    2026-05-07
2    2026-06-21
3    2026-02-18
4    2026-02-18
5    2026-03-23
6    2026-04-21
7    2026-05-21
8    2026-03-05
9    2026-06-13
Name: order_date, dtype: object

In [23]:
df['order_date'].dtype

dtype('O')

In [24]:
# Step --> 3. Standardize city names and product names using UrbanKart's official city list

In [25]:
df['city'].head(10)

0         Patna
1       Chennai
2     Bengaluru
3     Hyderabad
4        Raipur
5        Mumbai
6     Hyderabad
7       Chennai
8         Delhi
9    Chandigarh
Name: city, dtype: object

In [26]:
df['city'].tail(10)

5140     Chandigarh
5141          Noida
5142         Nagpur
5143      Ahmedabad
5144          Delhi
5145      Ahmedabad
5146           Pune
5147       Guwahati
5148    Bhubaneswar
5149    Bhubaneswar
Name: city, dtype: object

In [27]:
city_mapping={
    "Gurgoan":"Gurugram",
    "GGN":"Gurugram",
    "Banglore":"Bengaluru",
    "Bombay":"Mumbai",
    "Calcutta":"Kolkata",
    "Madras":"Chennai",
    "Cochin":"Kochi",
    "New Delhi":"Delhi"
}

In [28]:
df['city']=df['city'].replace(city_mapping)

In [29]:
df['city'].unique()

array(['Patna', 'Chennai', 'Bengaluru', 'Hyderabad', 'Raipur', 'Mumbai',
       'Delhi', 'Chandigarh', 'Noida', 'Bhubaneswar', 'Bhopal',
       'Ahmedabad', 'Guwahati', 'Nagpur', 'Kochi', 'Indore', 'Bangalore',
       'Pune', 'Surat', 'Gurugram', 'Kolkata', 'BLR', 'kochi', 'Gurgaon',
       'bengaluru', 'patna', 'raipur', 'CHANDIGARH', 'Mumbai   ',
       '  Kochi', 'chandigarh', 'Kolkata   ', 'Chandigarh   ', 'guwahati',
       'DELHI', 'chennai', 'surat', '  Ahmedabad', 'Surat   ',
       '  Chandigarh', '  Chennai', 'Chennai   ', 'Raipur   ', '  Noida',
       'Noida   ', '  Bhubaneswar', 'PUNE', 'Kochi   ', '  Surat',
       '  Bhopal', 'mumbai'], dtype=object)

In [30]:
sorted(df['product_name'].unique())

['  Badminton Racket Set',
 '  Cotton Bedsheet Set',
 '  Cricket Bat English Willow',
 '  Cycling Helmet',
 '  Mirrorless Camera Lite',
 '  Modern Wall Clock',
 '  Noise-Cancelling Headphones',
 '  Power Bank 20000mAh',
 '  Silk Saree',
 '  Vitamin C Serum',
 '  Wireless Earbuds Pro',
 '  Yoga Mat Pro',
 '43-inch Smart TV',
 'Adjustable Dumbbells 15kg',
 'Air Fryer 5L',
 'Badminton Racket Set',
 'Beard Grooming Kit',
 'Beard Grooming Kit   ',
 'Bluetooth Speaker Mini',
 'COTTON BEDSHEET SET',
 'COTTON KURTA SET',
 'Cotton Bedsheet Set',
 'Cotton Kurta Set',
 'Cotton Kurta Set   ',
 'Cricket Bat English Willow',
 'Cycling Helmet',
 'Denim Jacket',
 'Dinner Set 24pc',
 'Dinner Set 24pc   ',
 'ELECTRIC KETTLE 1.5L',
 'ETHNIC DUPATTA',
 'Eau de Parfum 100ml',
 'Electric Kettle 1.5L',
 'Electric Kettle 1.5L   ',
 'Ethnic Dupatta',
 'FACE WASH COMBO',
 'FORMAL SHIRT',
 'Face Wash Combo',
 'Foldable Treadmill T2',
 'Football Size 5',
 'Formal Shirt',
 'Formal Shirt   ',
 'Gym Gloves',
 'Ionic Hair Dryer',
 'Leather Wallet',
 'MIRRORLESS CAMERA LITE',
 'Makeup Brush Set',
 'Makeup Brush Set   ',
 'Matte Lipstick Set',
 'Mirrorless Camera Lite',
 'Mixer Grinder 750W',
 'Modern Wall Clock',
 'NON-STICK COOKWARE SET',
 'Noise-Cancelling Headphones',
 'Noise-Cancelling Headphones   ',
 'Non-Stick Cookware Set',
 'Power Bank 20000mAh',
 'Power Bank 20000mAh   ',
 'ROBOT VACUUM R7',
 'RUNNING SNEAKERS',
 'Robot Vacuum R7',
 'Robot Vacuum R7   ',
 'Running Sneakers',
 'Running Sneakers   ',
 'Silk Saree',
 'Silk Saree   ',
 'Slim Fit Jeans',
 'Slim Fit Jeans   ',
 'Smart Watch X2',
 'Sunscreen SPF50',
 'Ultrabook Air 14',
 'Ultrabook Air 14   ',
 'Vitamin C Serum',
 'WIRELESS EARBUDS PRO',
 'Wireless Earbuds Pro',
 'Wireless Earbuds Pro   ',
 'Yoga Mat Pro',
 'adjustable dumbbells 15kg',
 'badminton racket set',
 'bluetooth speaker mini',
 'cotton kurta set',
 'electric kettle 1.5l',
 'modern wall clock',
 'power bank 20000mah',
 'smart watch x2',
 'sunscreen spf50',
 'vitamin c serum',
 'wireless earbuds pro']

In [31]:
df['product_name']=df['product_name'].str.strip()

In [32]:
official_products = [
    "43-inch Smart TV",
    "Bluetooth Speaker Mini",
    "Mirrorless Camera Lite",
    "Noise-Cancelling Headphones",
    "Power Bank 20000mAh",
    "Smart Watch X2",
    "Ultrabook Air 14",
    "Wireless Earbuds Pro",

    "Cotton Kurta Set",
    "Denim Jacket",
    "Ethnic Dupatta",
    "Formal Shirt",
    "Leather Wallet",
    "Running Sneakers",
    "Silk Saree",
    "Slim Fit Jeans",

    "Air Fryer 5L",
    "Cotton Bedsheet Set",
    "Dinner Set 24pc",
    "Electric Kettle 1.5L",
    "Mixer Grinder 750W",
    "Modern Wall Clock",
    "Non-Stick Cookware Set",
    "Robot Vacuum R7",

    "Beard Grooming Kit",
    "Eau de Parfum 100ml",
    "Face Wash Combo",
    "Ionic Hair Dryer",
    "Makeup Brush Set",
    "Matte Lipstick Set",
    "Sunscreen SPF50",
    "Vitamin C Serum",

    "Adjustable Dumbbells 15kg",
    "Badminton Racket Set",
    "Cricket Bat English Willow",
    "Cycling Helmet",
    "Foldable Treadmill T2",
    "Football Size 5",
    "Gym Gloves",
    "Yoga Mat Pro"
]

In [33]:
product_mapping={product.lower():product for product in official_products}

In [34]:
df['product_name']=df['product_name'].str.lower().map(product_mapping)

In [35]:
sorted(df['product_name'].unique())

['43-inch Smart TV',
 'Adjustable Dumbbells 15kg',
 'Air Fryer 5L',
 'Badminton Racket Set',
 'Beard Grooming Kit',
 'Bluetooth Speaker Mini',
 'Cotton Bedsheet Set',
 'Cotton Kurta Set',
 'Cricket Bat English Willow',
 'Cycling Helmet',
 'Denim Jacket',
 'Dinner Set 24pc',
 'Eau de Parfum 100ml',
 'Electric Kettle 1.5L',
 'Ethnic Dupatta',
 'Face Wash Combo',
 'Foldable Treadmill T2',
 'Football Size 5',
 'Formal Shirt',
 'Gym Gloves',
 'Ionic Hair Dryer',
 'Leather Wallet',
 'Makeup Brush Set',
 'Matte Lipstick Set',
 'Mirrorless Camera Lite',
 'Mixer Grinder 750W',
 'Modern Wall Clock',
 'Noise-Cancelling Headphones',
 'Non-Stick Cookware Set',
 'Power Bank 20000mAh',
 'Robot Vacuum R7',
 'Running Sneakers',
 'Silk Saree',
 'Slim Fit Jeans',
 'Smart Watch X2',
 'Sunscreen SPF50',
 'Ultrabook Air 14',
 'Vitamin C Serum',
 'Wireless Earbuds Pro',
 'Yoga Mat Pro']

In [36]:
# Step --> 4. Fix total_revenue stored as text

In [37]:
df['total_revenue'].head(10)

0      1866
1       682
2      3107
3      1122
4      2196
5      1126
6      3082
7    110260
8     26675
9      9405
Name: total_revenue, dtype: object

In [38]:
df['total_revenue'].tail(10)

5140     1098
5141     1959
5142      897
5143      519
5144    59379
5145     2281
5146     1831
5147    28432
5148     3358
5149     2958
Name: total_revenue, dtype: object

In [39]:
df['total_revenue'].dtype

dtype('O')

In [40]:
df['total_revenue']=df['total_revenue'].str.replace('₹','',regex=False)

In [41]:
df['total_revenue']=df['total_revenue'].str.replace(',','',regex=False)

In [42]:
df['total_revenue']=df['total_revenue'].str.replace('INR','',regex=False)

In [43]:
df['total_revenue']=df['total_revenue'].str.strip()

In [44]:
df['total_revenue']=pd.to_numeric(df['total_revenue'])

In [45]:
df['total_revenue'].dtype

dtype('float64')

In [46]:
df['total_revenue'].head(20)

0       1866.0
1        682.0
2       3107.0
3       1122.0
4       2196.0
5       1126.0
6       3082.0
7     110260.0
8      26675.0
9       9405.0
10      1036.0
11     19221.0
12      5586.0
13      5574.0
14     19833.0
15      5455.0
16      1254.0
17     59006.0
18      1248.0
19      2888.0
Name: total_revenue, dtype: float64

In [47]:
# Step --> 5. Handle missing values

In [48]:
df.isnull().sum()

order_id          0
order_date        0
region           60
city              0
product_name      0
category          0
quantity         60
unit_price        0
total_revenue    60
customer_id       0
sales_channel     0
dtype: int64

In [49]:
df=df.dropna(subset=['quantity','total_revenue']).copy()

In [50]:
df.isnull().sum()

order_id          0
order_date        0
region           60
city              0
product_name      0
category          0
quantity          0
unit_price        0
total_revenue     0
customer_id       0
sales_channel     0
dtype: int64

In [51]:
city_region = {
    "Delhi": "North",
    "Gurugram": "North",
    "Noida": "North",
    "Chandigarh": "North",

    "Bengaluru": "South",
    "Chennai": "South",
    "Hyderabad": "South",
    "Kochi": "South",

    "Mumbai": "West",
    "Pune": "West",
    "Ahmedabad": "West",
    "Surat": "West",

    "Kolkata": "East",
    "Bhubaneswar": "East",
    "Guwahati": "East",
    "Patna": "East",

    "Indore": "Central",
    "Bhopal": "Central",
    "Nagpur": "Central",
    "Raipur": "Central"
}

In [52]:
df['region']=df['region'].fillna(df['city'].map(city_region))

In [53]:
df.isnull().sum()

order_id         0
order_date       0
region           0
city             0
product_name     0
category         0
quantity         0
unit_price       0
total_revenue    0
customer_id      0
sales_channel    0
dtype: int64

In [54]:
# Step --> 6. Remove invalid quantities

In [55]:
(df['quantity']<=0).sum()

np.int64(60)

In [56]:
df=df[df['quantity']>0].copy()

In [57]:
(df['quantity']<=0).sum()

np.int64(0)

In [58]:
# Step --> 7. Fix whitespace and casing

In [59]:
df['city']=df['city'].str.strip()

In [60]:
official_cities = [
    "Delhi",
    "Gurugram",
    "Noida",
    "Chandigarh",
    "Bengaluru",
    "Chennai",
    "Hyderabad",
    "Kochi",
    "Mumbai",
    "Pune",
    "Ahmedabad",
    "Surat",
    "Kolkata",
    "Bhubaneswar",
    "Guwahati",
    "Patna",
    "Indore",
    "Bhopal",
    "Nagpur",
    "Raipur"
]

In [61]:
city_lookup={city.lower() : city for city in official_cities}

In [62]:
df['city']=df['city'].str.lower().map(city_lookup)

In [63]:
df['city'].head(10)

0          Patna
1        Chennai
2      Bengaluru
3      Hyderabad
4         Raipur
5         Mumbai
6      Hyderabad
8          Delhi
9     Chandigarh
10         Delhi
Name: city, dtype: object

In [64]:
df['product_name']=df['product_name'].str.strip()

In [65]:
df['product_name']=df['product_name'].str.lower().map(product_mapping)

In [66]:
df['product_name'].head(10)

0              Matte Lipstick Set
1                 Vitamin C Serum
2            Wireless Earbuds Pro
3            Electric Kettle 1.5L
4                    Denim Jacket
5            Electric Kettle 1.5L
6          Bluetooth Speaker Mini
8                43-inch Smart TV
9     Noise-Cancelling Headphones
10                 Ethnic Dupatta
Name: product_name, dtype: object

In [67]:
sorted(df["product_name"].unique())

['43-inch Smart TV',
 'Adjustable Dumbbells 15kg',
 'Air Fryer 5L',
 'Badminton Racket Set',
 'Beard Grooming Kit',
 'Bluetooth Speaker Mini',
 'Cotton Bedsheet Set',
 'Cotton Kurta Set',
 'Cricket Bat English Willow',
 'Cycling Helmet',
 'Denim Jacket',
 'Dinner Set 24pc',
 'Eau de Parfum 100ml',
 'Electric Kettle 1.5L',
 'Ethnic Dupatta',
 'Face Wash Combo',
 'Foldable Treadmill T2',
 'Football Size 5',
 'Formal Shirt',
 'Gym Gloves',
 'Ionic Hair Dryer',
 'Leather Wallet',
 'Makeup Brush Set',
 'Matte Lipstick Set',
 'Mirrorless Camera Lite',
 'Mixer Grinder 750W',
 'Modern Wall Clock',
 'Noise-Cancelling Headphones',
 'Non-Stick Cookware Set',
 'Power Bank 20000mAh',
 'Robot Vacuum R7',
 'Running Sneakers',
 'Silk Saree',
 'Slim Fit Jeans',
 'Smart Watch X2',
 'Sunscreen SPF50',
 'Ultrabook Air 14',
 'Vitamin C Serum',
 'Wireless Earbuds Pro',
 'Yoga Mat Pro']

In [68]:
# Self-check

In [69]:
df['expected_revenue']=df['quantity']*df['unit_price']

In [70]:
invalid_rows=df[df['expected_revenue']!=df['total_revenue']]

In [71]:
len(invalid_rows)

0

In [72]:
df=df.drop(columns=['expected_revenue'])

In [73]:
df.dtypes

order_id          object
order_date        object
region            object
city              object
product_name      object
category          object
quantity         float64
unit_price         int64
total_revenue    float64
customer_id       object
sales_channel     object
dtype: object

In [74]:
df['quantity']=df['quantity'].astype(int)

In [75]:
df['total_revenue']=df['total_revenue'].astype(int)

In [76]:
df.dtypes

order_id         object
order_date       object
region           object
city             object
product_name     object
category         object
quantity          int64
unit_price        int64
total_revenue     int64
customer_id      object
sales_channel    object
dtype: object

In [77]:
df.to_csv("urbankart_sales_clean.csv", index=False)

In [78]:
df.shape

(4820, 11)